### ISSUE TITLE
Create a simple website for Starknet Gas Tracker.

### ISSUE THREAD

**Issue by cryptonerdcn** [ConstLabs/Starknet-gas-price-browser-extension#1]
Some users may hesitate to install an extension for security reasons, although this extension is completely safe cause it does not have the ability to read any information from the user.

We can make a simple website for these users.
No backend is needed, just use the same logic of this browser extension.

**Comment by Ayoazeez26** [comment]
Hi @cryptonerdcn , I'd like to jump on this if that's fine

**Comment by cryptonerdcn** [comment]
Hi @Ayoazeez26, thanks for your comment! 
@gaetbout also talked to me on TG on Monday, so maybe you can discuss this task first?

**Comment by gaetbout** [comment]
gm gm, 
Feel free to assign it to him, atm my agenda is too full :(

**Comment by Ayoazeez26** [comment]
@cryptonerdcn is there a figma design yet for the website?

**Comment by cryptonerdcn** [comment]
@Ayoazeez26 We don't. But you can take a look at this: https://www.blocknative.com/gas-estimator
And please use React(with Next.js or Vite.js) + tailwind if it is possible because I only know these.

**Comment by Ayoazeez26** [comment]
I'll send you a DM on twitter for more info and clarifications

**Comment by cryptonerdcn** [comment]
> I'll send you a DM on twitter for more info and clarifications

Hi my tg handle is same as my github handle.

**Comment by ktarun1419** [comment]
Hi i want to contribute to this

**Comment by IanVargas** [comment]
Hi @cryptonerdcn  is there someone working on this?, I would like to jump on this one and help you with it. Let me know and we could jump on it

**Comment by cryptonerdcn** [comment]
Finished.

https://starknet-gas-landing.vercel.app/
